# Generated by Django 6.0.4 on 2026-04-26 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True, verbose_name='название института')),
            ],
            options={
                'verbose_name': 'институт',
                'verbose_name_plural': 'институты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.PositiveSmallIntegerField(verbose_name='курс')),
                ('name', models.CharField(max_length=80, verbose_name='название группы')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='pages.institute', verbose_name='институт')),
            ],
            options={
                'verbose_name': 'учебная группа',
                'verbose_name_plural': 'учебные группы',
                'ordering': ['institute__name', 'course', 'name'],
                'unique_together': {('institute', 'course', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата занятия')),
                ('start_time', models.TimeField(verbose_name='начало')),
                ('end_time', models.TimeField(verbose_name='конец')),
                ('subject', models.CharField(max_length=180, verbose_name='дисциплина')),
                ('teacher', models.CharField(blank=True, max_length=140, verbose_name='преподаватель')),
                ('room', models.CharField(blank=True, max_length=60, verbose_name='аудитория')),
                ('note', models.TextField(blank=True, verbose_name='заметка')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='pages.studygroup', verbose_name='группа')),
            ],
            options={
                'verbose_name': 'занятие',
                'verbose_name_plural': 'занятия',
                'ordering': ['date', 'start_time', 'subject'],
            },
        ),
    ]
